name: Update README with Simkl

on:
  schedule:
    - cron: "0 7 * * *"  # Every day at 07:00 UTC (08:00 in Portugal during summer)
  workflow_dispatch:      # Allows manual run from GitHub interface

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install feedparser requests

    - name: Run script to update README
      run: python simkl_feed.py

    - name: Commit changes if any
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add README.md
        git diff --cached --quiet || git commit -m "🤖 Update README with Simkl data"
        git push
