name: Update README with Simkl

on:
  schedule:
    - cron: "0 7 * * *"  # Every day 07:00 UTC
  workflow_dispatch:        # Allows manual run from GitHub interface

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser requests

      - name: Run script to update README
        env:
          SIMKL_CLIENT_ID: ${{ secrets.SIMKL_CLIENT_ID }}
          SIMKL_ACCESS_TOKEN: ${{ secrets.SIMKL_ACCESS_TOKEN }}
        run: python scripts/simkl_feed.py

      - name: Commit changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          if ! git diff --cached --quiet; then
            git commit -m "🤖 Update README with Simkl data"
            git pull --rebase origin main
            git push
          else
            echo "No changes to commit"
          fi
